CREATE TABLE location_events(
    accuracy INT,
    altitude INT,
    battery_level INT,
    battery_status INT,
    course_over_ground INT,
    latitude FLOAT,
    longitude FLOAT,
    radius INT,
    trigger_type VARCHAR(1),
    tracker_id VARCHAR(255),
    timestamp INT,
    vertical_accuracy INT,
    velocity INT,
    barometric_pressure FLOAT,
    point_of_interest VARCHAR(255),
    connectivity_status VARCHAR(1),
    tag_name VARCHAR(255),
    original_publish_topic VARCHAR(255),
    regions_currently_in JSONB,
    region_ids_currently_in JSONB,
    wifi_ssid VARCHAR(255),
    wifi_bssid VARCHAR(255),
    message_creation_time TIMESTAMP,
    monitoring_mode INT
);